---
title: "Honors Thesis Working Document"
author: "Boston Lee"
date: "9/19/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(knitr)
library(tidyverse)
# library(tidycensus)
```

# EDA

## Numerical summaries

```{r read-data}
mental_health_df <- read_csv("../data/preprocessed/mental_health_2018.csv")
```

```{r summarize-func}

#' Given a dataframe, return a column-level summary of the mean and sd
#' of the numeric columns
#'
#' @param df A dataframe with numeric columns
#' @return A dataframe with three columns: name_col (column name), sd, and mean
summarize_data <- function(df) {
  funcs <- list(mean = ~ mean(.x), sd = ~ sd(.x))
  mean_df <- summarize_func(df, "mean")
  sd_df <- summarize_func(df, "sd")
  full_summary <- inner_join(mean_df, sd_df, by = "col_name")
  return(full_summary)
}

#' Given a dataframe, return a column-level summary of the mean and sd
#' of the numeric columns
#'
#' @param df A dataframe with numeric columns
#' @return A dataframe with two columns: The original column name and the
#'   func summary of the original (numeric) column values
summarize_func <- function(df, func_name) {
  func <- get(func_name)
  namestring <- paste(func_name, "{.col}", sep = "")
  func_df <- df %>%
    summarize(across(where(is.numeric), func, .names = namestring)) %>%
    pivot_longer(
      cols = starts_with(func_name),
      names_to = "col_name",
      names_prefix = func_name,
      values_to = func_name,
      values_drop_na = FALSE
    )

  return(func_df)
}
```

```{r summary-table}
summarize_data(mental_health_df) %>%
  column_to_rownames("col_name") %>%
  kable()
```

## Visualization

```{r hist-func}

#' Given a dataframe and a variable name, return a ggplot histogram of the
#' named variable
#'
#' @param df A dataframe
#' @param variable A variable name (string) which is a column of \code{df}
#' @return A ggplot2 object
histogram_variable <- function(df, variable) {
  plot <- ggplot(data = df) +
    theme_bw() +
    geom_histogram(aes_string(variable), fill = "seagreen", color = "black") +
    ggtitle(sprintf("Histogram of %s", variable)) +
    xlab(variable)
  return(plot)
}
```

```{r generate-boxplots}
column_names <- colnames(mental_health_df)
inds <- sapply(mental_health_df, is.numeric)
for (i in seq_len(length(colnames(mental_health_df)))) {
  varname <- column_names[i]
  if (inds[i]) {
    plot <- histogram_variable(mental_health_df, varname)
    ggsave(paste("./plots/", varname, "_boxplot.png", sep = ""), plot)
    print(plot)
  }
}
```

```{r map-func-county}
map_var <- function(mental_health_df, var_name) {
  # Grab county FIPS, pad with zeros to match data, and pull out columns
  maps::county.fips %>%
    as_tibble() %>%
    mutate(fips = str_pad(fips, 5, "left", "0")) %>%
    extract(polyname, c("region", "subregion"), "^([^,]+),([^,]+)$") ->
  fips_df
  head(fips_df)
  # Join county map objects with FIPS, and then use that linkage
  # to join the mental health data
  map_data("county") %>%
    left_join(fips_df) %>%
    left_join(mental_health_df) ->
  fips_county_df
  head(fips_county_df)
  # Plot overall
  fips_county_df %>%
    ggplot(aes(long, lat, group = group)) +
    geom_polygon(aes_string(fill = var_name), color = "gray70", size = 0.15) +
    coord_map() +
    ggtitle(paste("Map of ", var_name, " across the United States")) +
    scale_fill_distiller(palette = "Spectral")
}
```

```{r map-samhsa}
samhsa_vars <- c(
  "prop_suicidal_thoughts",
  "prop_MDE",
  "prop_alcohol_use_disorder"
)
for (samhsa_var in samhsa_vars) {
  map_plot <- map_var(mental_health_df, samhsa_var)
  print(map_plot)
  ggsave(paste("./maps/", samhsa_var, "_map.png", sep = ""), map_plot)
}
```

```{r map-acs}
acs_vars <- c(
  "prop_below_poverty_level",
  "median_household_income"
)
for (acs_var in acs_vars) {
  map_plot <- map_var(mental_health_df, acs_var)
  print(map_plot)
  ggsave(paste("./maps/", acs_var, "_map.png", sep = ""), map_plot)
}
```
